Rails.application.routes.draw do
  get '/persons' => 'persons#index'
  get '/cats' => 'cats#index'
  get '/dogs' => 'dogs#index'
  get '/teachers' => 'teachers#index'
  get '/students' => 'students#index'
  get '/persons/:id' => 'persons#show'
  get '/cats/:id' => 'cats#show'
  get '/dogs/:id' => 'dogs#show'
  get '/teachers/:id' => 'teachers#show'
  get '/students/:id' => 'students#show'
  post '/persons' => 'persons#create'
  post '/cats' => 'cats#create'
  post '/dogs' => 'dogs#create'
  post '/teachers' => 'teachers#create'
  post '/students' => 'students#create'
  put '/persons/:id' => 'persons#update'
  put '/cats/:id' => 'cats#update'
  put '/dogs/:id' => 'dogs#update'
  put '/teachers/:id' => 'teachers#update'
  put '/students/:id' => 'students#update'
  delete '/persons/:id' => 'persons#destroy'
  delete '/cats/:id' => 'cats#destroy'
  delete '/dogs/:id' => 'dogs#destroy'
  delete '/teachers/:id' => 'teachers#destroy'
  delete '/students/:id' => 'students#destroy'
end