Rails.application.routes.draw do
  get '/persons' => 'persons#index'
  get '/cats' => 'cats#index'
  get '/dogs' => 'dogs#index'
  get '/teachers' => 'teachers#index'
  get '/students' => 'students#index'
  get '/persons/:id' => 'persons#show'
  get '/cats/:id' => 'cats#show'
  get '/dogs/:id' => 'dogs#show'
  get '/teachers/:id' => 'teachers#show'
  get '/students/:id' => 'students#show'
  post '/persons' => 'persons#create'
  post '/cats' => 'cats#create'
  post '/dogs' => 'dogs#create'
  post '/teachers' => 'teachers#create'
  post '/students' => 'students#create'
end