Person.create(name: "Jane Doe", age: 23)
Person.create(name: "John Doe", age: 43)
Person.create(name: "Alice Johnson", age: 29)
Person.create(name: "Cassandra Schalts", age: 40)
Person.create(name: "Dalton Harrington", age: 36)
Teacher.create(grade: 100, subject: "Coding")
Teacher.create(grade: 99, subject: "Health")
Teacher.create(grade: 103, subject: "English Honors")
Teacher.create(grade: 110, subject: "Social Studies Honors")
Teacher.create(grade: 109, subject: "Geometry Honors")
Student.create(grade: 97.5, name: "Alice")
Student.create(grade: 96, name: "Bob")
Student.create(grade: 95.8, name: "Carl")
Student.create(grade: 98, name: "Diana")
Student.create(grade: 99, name: "Earl")
Dog.create(breed: "Doberman", color: "Black")
Cat.create(breed: "Domestic Shorthair", color: "Calico")